<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Kitsune</AssemblyName>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Version>1.0.1</Version>
	<Copyright>GesthosNetwork © 2026 All rights reserved.</Copyright>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>false</PublishTrimmed>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishDir>.\bin\</PublishDir>
    <ApplicationIcon>Core\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Tools\hpatchz.exe" />
    <EmbeddedResource Include="Tools\7z.exe" />
  </ItemGroup>

  <Target Name="PostPublishCleanup" AfterTargets="Publish">
    <ItemGroup>
      <FilesToDelete Include="$(PublishDir)**\*.pdb" />
    </ItemGroup>

    <Delete Files="@(FilesToDelete)" />
    <RemoveDir Directories="$(ProjectDir)bin\Release;$(ProjectDir)obj" />
  </Target>

</Project>
